//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 02:02:36 PM EDT 
//


package gov.uspto.patent.privatePair.score.scoreService.MegaData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mega-item-record-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mega-item-record-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mega-item-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mega-item-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="item-total" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="process-code" type="{http://webservices.score.uspto.gov/}megaItemProcessCodeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="item-size" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="mailroomDateText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mega-item-record-type", propOrder = {
    "megaItemId",
    "megaItemName",
    "itemTotal",
    "processCode",
    "itemSize",
    "mailroomDateText"
})
public class MegaItemRecordType {

    @XmlElement(name = "mega-item-id", required = true)
    protected String megaItemId;
    @XmlElement(name = "mega-item-name", required = true)
    protected String megaItemName;
    @XmlElement(name = "item-total")
    protected String itemTotal;
    @XmlElement(name = "process-code")
    protected List<MegaItemProcessCodeType> processCode;
    @XmlElement(name = "item-size")
    protected long itemSize;
    protected String mailroomDateText;

    /**
     * Gets the value of the megaItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegaItemId() {
        return megaItemId;
    }

    /**
     * Sets the value of the megaItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegaItemId(String value) {
        this.megaItemId = value;
    }

    /**
     * Gets the value of the megaItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegaItemName() {
        return megaItemName;
    }

    /**
     * Sets the value of the megaItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegaItemName(String value) {
        this.megaItemName = value;
    }

    /**
     * Gets the value of the itemTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemTotal() {
        return itemTotal;
    }

    /**
     * Sets the value of the itemTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemTotal(String value) {
        this.itemTotal = value;
    }

    /**
     * Gets the value of the processCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MegaItemProcessCodeType }
     * 
     * 
     */
    public List<MegaItemProcessCodeType> getProcessCode() {
        if (processCode == null) {
            processCode = new ArrayList<MegaItemProcessCodeType>();
        }
        return this.processCode;
    }

    /**
     * Gets the value of the itemSize property.
     * 
     */
    public long getItemSize() {
        return itemSize;
    }

    /**
     * Sets the value of the itemSize property.
     * 
     */
    public void setItemSize(long value) {
        this.itemSize = value;
    }

    /**
     * Gets the value of the mailroomDateText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailroomDateText() {
        return mailroomDateText;
    }

    /**
     * Sets the value of the mailroomDateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailroomDateText(String value) {
        this.mailroomDateText = value;
    }

}
