//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 06:07:48 PM EDT 
//


package gov.uspto.patent.privatePair.score.scoreService.MegaItemVersionHistory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mega-item-version-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mega-item-version-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="version-number" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="subversion-number" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="sequence-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="best-copy-indicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mega-item-version-type", propOrder = {
    "versionNumber",
    "subversionNumber",
    "sequenceId",
    "bestCopyIndicator"
})
public class MegaItemVersionType {

    @XmlElement(name = "version-number")
    protected int versionNumber;
    @XmlElement(name = "subversion-number")
    protected Integer subversionNumber;
    @XmlElement(name = "sequence-id")
    protected String sequenceId;
    @XmlElement(name = "best-copy-indicator")
    protected boolean bestCopyIndicator;

    /**
     * Gets the value of the versionNumber property.
     * 
     */
    public int getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     */
    public void setVersionNumber(int value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the subversionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubversionNumber() {
        return subversionNumber;
    }

    /**
     * Sets the value of the subversionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubversionNumber(Integer value) {
        this.subversionNumber = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the bestCopyIndicator property.
     * 
     */
    public boolean isBestCopyIndicator() {
        return bestCopyIndicator;
    }

    /**
     * Sets the value of the bestCopyIndicator property.
     * 
     */
    public void setBestCopyIndicator(boolean value) {
        this.bestCopyIndicator = value;
    }

}
