CREATE 	TABLE 	APPLICATION_CUST_CHNG_RQST (
APPLICATION_CUST_CHNG_RQST_ID			NUMBER(15)					PRIMARY KEY,
  FK_USER_REQUEST_ID			        NUMBER(15)		            NOT NULL,		
  APPLICATION_ID 			        	VARCHAR2(17),
  CUSTOMER_NO 			        	    NUMBER(9),
  PATENT_NO		        	        	VARCHAR2(10),
  CORR_ADDR_CHANGE_IN					VARCHAR2(1),
  MAINT_FEE_ADDR_CHANGE_IN	  			VARCHAR2(1),
  POWER_OF_ATTORNEY_IN		  			VARCHAR2(1),
  ATTORNEY_AUTHORIZATION_IN				VARCHAR2(1),
  INPUT_SOURCE_CT  						VARCHAR2(15),
  REQUEST_ERROR_TX						VARCHAR2(256)
     );

ALTER 	TABLE 	APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT RI_UR_ACCR
FOREIGN KEY (FK_USER_REQUEST_ID)
REFERENCES USER_REQUEST(USER_REQUEST_ID);

CREATE SEQUENCE PK_APP_CUST_CHNG_RQST_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
/
CREATE OR REPLACE TRIGGER 	PK_APP_CUST_CHNG_RQST_TRIGGER
  BEFORE INSERT ON APPLICATION_CUST_CHNG_RQST
 FOR EACH ROW
BEGIN
  SELECT PK_APP_CUST_CHNG_RQST_SEQ.nextval
    INTO :new.APPLICATION_CUST_CHNG_RQST_ID
    FROM dual;
END;
/

ALTER TABLE APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT  CK_APPL_CUST_CHNG_RQST_AUTH
  CHECK (ATTORNEY_AUTHORIZATION_IN   IN ('Y', 'N'));
  
ALTER TABLE APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT  CK_APPL_CUST_CHNG_RQST_CORR
  CHECK (CORR_ADDR_CHANGE_IN   IN ('1', '0'));
  
ALTER TABLE APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT  CK_APPL_CUST_CHNG_RQST_MAINT
  CHECK (MAINT_FEE_ADDR_CHANGE_IN   IN ('1', '0'));
  
ALTER TABLE APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT  CK_APPL_CUST_CHNG_RQST_POWER
  CHECK (POWER_OF_ATTORNEY_IN   IN ('1', '0'));
  
 ALTER TABLE APPLICATION_CUST_CHNG_RQST
ADD CONSTRAINT  CK_APPL_CUST_CHNG_RQST_INPUT
  CHECK (INPUT_SOURCE_CT   IN ('BULK', 'ELECTRONIC'));
  
COMMENT ON TABLE APPLICATION_CUST_CHNG_RQST IS 'Table to store the customer correspondence address mapping changes as draft in PAIR database until customer submits to make final changes in PALM database.  Once the final submission is made to PALM the records are used as audit logs for any future customer queries.';

COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.FK_USER_REQUEST_ID	IS 'Foreign key mapped to USER_REQUEST table ';  
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.APPLICATION_CUST_CHNG_RQST_ID	IS 'Primary Key '; 
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.CUSTOMER_NO	IS 'Associated customer number ';  
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.APPLICATION_ID	IS 'Application number.';  
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.PATENT_NO	IS 'Patent number.';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.CORR_ADDR_CHANGE_IN	IS 'Indicator to change correspondence address or not ';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.MAINT_FEE_ADDR_CHANGE_IN	IS 'Indicator to change maintenance address or not.';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.POWER_OF_ATTORNEY_IN	IS 'Indicator whether submitter is POA or not.';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.ATTORNEY_AUTHORIZATION_IN	IS 'Attornet cert check value.';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.INPUT_SOURCE_CT	IS 'Source of Update Address Change request BULK/ELECTRONIC.';
COMMENT ON COLUMN 	APPLICATION_CUST_CHNG_RQST.REQUEST_ERROR_TX	IS 'Any error message text.';
