CREATE 	TABLE 	CUSTOMER_NUMBER_REQUEST (
  CUSTOMER_NUMBER_REQUEST_ID			NUMBER(15) PRIMARY KEY,
  FK_USER_REQUEST_ID			        NUMBER(15)		            NOT NULL,		 
  CUSTOMER_NO 			        	    NUMBER(9),
  NAME_LINE_ONE_TX		        	    VARCHAR2(50),
  NAME_LINE_TWO_TX		        	    VARCHAR2(50),
  ADDRESS_LINE_ONE_TX		        	VARCHAR2(50),
  ADDRESS_LINE_TWO_TX		        	VARCHAR2(50),
  CITY_NM				        	    VARCHAR2(40),
  CFK_GEOGRAPHIC_REGION_CD				VARCHAR2(3),
  POSTAL_CD				        	    VARCHAR2(20),
  CFK_COUNTRY_CD				        VARCHAR2(3),
  TELEPHONE_NO_ONE_TX					VARCHAR2(25),
  TELEPHONE_NO_TWO_TX					VARCHAR2(25),
  TELEPHONE_NO_THREE_TX					VARCHAR2(25),
  EMAIL_ADDRESS_ONE_TX					VARCHAR2(129),
  EMAIL_ADDRESS_TWO_TX					VARCHAR2(129),
  EMAIL_ADDRESS_THREE_TX				VARCHAR2(129),
  FAX_NO_ONE_TX							VARCHAR2(25),
  FAX_NO_TWO_TX							VARCHAR2(25),
  ASSOCIATED_REG_NO_IN					CHAR(1),
  OA_ENROLLMENT_CT						VARCHAR2(5)
    );
	

ALTER 	TABLE 	CUSTOMER_NUMBER_REQUEST
ADD CONSTRAINT RI_UR_CNR
FOREIGN KEY (FK_USER_REQUEST_ID)
REFERENCES USER_REQUEST(USER_REQUEST_ID);

CREATE SEQUENCE PK_CUSTOMER_NUMBER_REQ_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
 /
CREATE OR REPLACE TRIGGER 	PK_CUSTOMER_NUMBER_REQ_TRIGGER
  BEFORE INSERT ON CUSTOMER_NUMBER_REQUEST
 FOR EACH ROW
BEGIN
  SELECT PK_CUSTOMER_NUMBER_REQ_SEQ.nextval
    INTO :new.CUSTOMER_NUMBER_REQUEST_ID
    FROM dual;
END;
/

ALTER TABLE CUSTOMER_NUMBER_REQUEST
ADD CONSTRAINT  CK_CNR_EMAIL_OA_ENROLLMENT
  CHECK (OA_ENROLLMENT_CT   IN ('Email', 'Mail'));
  
ALTER TABLE CUSTOMER_NUMBER_REQUEST
ADD CONSTRAINT  CK_CNR_ASSOCIATED_REG_NO
  CHECK (ASSOCIATED_REG_NO_IN   IN ('Y', 'N'));

COMMENT ON TABLE CUSTOMER_NUMBER_REQUEST IS 'Table to store the customer address details changes as draft in PAIR database until customer submits to make final changes in PALM database.Once the final submission is made to PALM the records are used as audit logs for any future customer queries.';

COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.FK_USER_REQUEST_ID	IS 'Foreign key mapped to USER_REQUEST table ';  
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.CUSTOMER_NO	IS 'Customer Number that will be created new.';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.NAME_LINE_ONE_TX	IS 'Customer Details name line 1 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.NAME_LINE_TWO_TX	IS 'Customer Details name line 2 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.ADDRESS_LINE_ONE_TX	IS 'Customer Details adress line 1 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.ADDRESS_LINE_TWO_TX	IS 'Customer Details address line 2 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.CITY_NM	IS 'Customer Details city name ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.CFK_GEOGRAPHIC_REGION_CD	IS 'Customer Details state code ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.POSTAL_CD	IS 'Customer Details postal code ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.CFK_COUNTRY_CD	IS 'Customer Details counrty code ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.TELEPHONE_NO_ONE_TX	IS 'Customer Details Telephone Number 1';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.TELEPHONE_NO_TWO_TX	IS 'Customer Details Telephone Number 2';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.TELEPHONE_NO_THREE_TX	IS 'Customer Details Telephone Number 3';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.EMAIL_ADDRESS_ONE_TX	IS 'Customer Details email 1 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.EMAIL_ADDRESS_TWO_TX	IS 'Customer Details email 2 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.EMAIL_ADDRESS_THREE_TX	IS 'Customer Details email 3 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.FAX_NO_ONE_TX	IS 'Customer Details fax 1 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.FAX_NO_TWO_TX	IS 'Customer Details fax 2 ';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.ASSOCIATED_REG_NO_IN	IS 'Customer Details: Indicates whether user associated RN or not';
COMMENT ON COLUMN 	CUSTOMER_NUMBER_REQUEST.OA_ENROLLMENT_CT	IS 'Receive correspondence via Mail/Email';


