CREATE 	TABLE 	CUSTOMER_CORR_ADDRESS (
  CUSTOMER_CORR_ADDRESS_ID				NUMBER(15) 				PRIMARY KEY,
  FK_USER_REQUEST_ID			        NUMBER(15)		        NOT NULL,		 
  CUSTOMER_NO 			        	    NUMBER(9)				NOT NULL,
  NAME_LINE_ONE_TX		        	    VARCHAR2(150),
  NAME_LINE_TWO_TX		        	    VARCHAR2(150),
  ADDRESS_LINE_ONE_TX		        	VARCHAR2(50),
  ADDRESS_LINE_TWO_TX		        	VARCHAR2(50),
  CITY_NM				        	    VARCHAR2(40),
  GEOGRAPHIC_REGION_NM					VARCHAR2(150),
  POSTAL_CD				        	    VARCHAR2(20),
  COUNTRY_NM			        		VARCHAR2(60)
    );
	

ALTER 	TABLE 	CUSTOMER_CORR_ADDRESS
ADD CONSTRAINT RI_UR_CCA
FOREIGN KEY (FK_USER_REQUEST_ID)
REFERENCES USER_REQUEST(USER_REQUEST_ID);

CREATE SEQUENCE PK_CUSTOMER_CORR_ADDR_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
 /
CREATE OR REPLACE TRIGGER 	PK_CUSTOMER_CORR_ADDR_TRIGGER
  BEFORE INSERT ON CUSTOMER_CORR_ADDRESS
 FOR EACH ROW
BEGIN
  SELECT PK_CUSTOMER_CORR_ADDR_SEQ.nextval
    INTO :new.CUSTOMER_CORR_ADDRESS_ID
    FROM dual;
END;
/

COMMENT ON TABLE CUSTOMER_CORR_ADDRESS IS 'Table to store the customer correspondence address details changes as draft in PAIR database after customer submits to make final changes in PALM database.
 This data is used only to view PAIR Admin/PURM update address submitted requests.';

COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.FK_USER_REQUEST_ID	IS 'Foreign key mapped to USER_REQUEST table ';  
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.CUSTOMER_NO	IS 'Customer Number that will be created new.';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.NAME_LINE_ONE_TX	IS 'Correspondence Address name line 1 ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.NAME_LINE_TWO_TX	IS 'Correspondence Address name line 2 ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.ADDRESS_LINE_ONE_TX	IS 'Correspondence Address address line 1 ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.ADDRESS_LINE_TWO_TX	IS 'Correspondence Address address line 2 ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.CITY_NM	IS 'Correspondence Address city name ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.GEOGRAPHIC_REGION_NM	IS 'Correspondence Address state code ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.POSTAL_CD	IS 'Correspondence Address postal code ';
COMMENT ON COLUMN 	CUSTOMER_CORR_ADDRESS.COUNTRY_NM	IS 'Correspondence Address country code ';