CREATE 	TABLE 	ENTITY_CHANGE_REQUEST (
  ENTITY_CHANGE_REQUEST_ID				NUMBER(15)	PRIMARY KEY,
  FK_USER_REQUEST_ID			        NUMBER(15)		            NOT NULL,		 
  APPLICATION_ID 			        	VARCHAR2(17)		        NOT NULL,
  INVENTION_TITLE_TX 			        VARCHAR2(600),
  CUSTOMER_NO 			        	    NUMBER(9),
  ATTORNEY_DOCKET_NO		        	VARCHAR2(17),
  PROPOSED_BUSINESS_ENTITY_CT			VARCHAR2(20),
  CURRENT_BUSINESS_ENTITY_CT	  		VARCHAR2(20)					  NOT NULL,
  MICRO_ENTITY_TYPE_CT  				VARCHAR2(30),
  MICRO_ENTITY_GROSS_CERTIF_IN	  		VARCHAR2(5),
  MICRO_ENTITY_INST_CERTIF_CT	  		VARCHAR2(35)
    );

ALTER 	TABLE 	ENTITY_CHANGE_REQUEST
ADD CONSTRAINT RI_UR_ECR
FOREIGN KEY (FK_USER_REQUEST_ID)
REFERENCES USER_REQUEST(USER_REQUEST_ID);

CREATE SEQUENCE PK_ENTITY_CHANGE_REQUEST_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
/
CREATE OR REPLACE TRIGGER 	PK_ENTITY_CHANGE_REQ_TRIGGER
  BEFORE INSERT ON ENTITY_CHANGE_REQUEST
 FOR EACH ROW
BEGIN
  SELECT PK_ENTITY_CHANGE_REQUEST_SEQ.nextval
    INTO :new.ENTITY_CHANGE_REQUEST_ID
    FROM dual;
END;
/

ALTER TABLE ENTITY_CHANGE_REQUEST
ADD CONSTRAINT  CK_ECR_PROPOSED_BUSINESS
  CHECK (PROPOSED_BUSINESS_ENTITY_CT   IN ('MicroEntityStatus','RegularEntityStatus', 'SmallEntityStatus'));
  
 ALTER TABLE ENTITY_CHANGE_REQUEST
ADD CONSTRAINT  CK_ECR_MICRO_ENTITY_TYPE
  CHECK (MICRO_ENTITY_TYPE_CT   IN ('GrossIncomeBasis','InstitutionOfHigherEdBasis'));
  
ALTER TABLE ENTITY_CHANGE_REQUEST
ADD CONSTRAINT  CK_ECR_MICRO_ENTITY_GROSS_CERT
  CHECK (MICRO_ENTITY_GROSS_CERTIF_IN   IN ('true','false'));
  
  ALTER TABLE ENTITY_CHANGE_REQUEST
ADD CONSTRAINT  CK_ECR_MICRO_ENTITY_INST
  CHECK (MICRO_ENTITY_INST_CERTIF_CT   IN ('InstitutionOfHigherEdBasisCert1','InstitutionOfHigherEdBasisCert2'));
 
COMMENT ON TABLE ENTITY_CHANGE_REQUEST IS 'Table to store the entity change details changes as draft in PAIR database until the user submits to make final changes in PALM database.Once the final submission is made to PALM the records are used as audit logs for any future user queries.';

COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.FK_USER_REQUEST_ID	IS 'Foreign key mapped to USER_REQUEST table ';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.APPLICATION_ID	IS 'Application Number for which the entity status is changed';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.INVENTION_TITLE_TX	IS 'Title of the application retrieved from PAIR/PALM.';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.CUSTOMER_NO	IS 'Customer Number that the application belongs to and retrieved from PAIR/PALM.';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.ATTORNEY_DOCKET_NO	IS 'Attorney Docket Number retrieved from PAIR/PALM.';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.CURRENT_BUSINESS_ENTITY_CT	IS 'Current Entity status value retrieved from PAIR/PALM.'; 
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.PROPOSED_BUSINESS_ENTITY_CT	IS 'New Entity status value MicroEntityStatus/SmallEntityStatus/RegularEntityStatus ';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.MICRO_ENTITY_TYPE_CT	IS 'Micro entity status category GrossIncomeBasis/InstitutionOfHigherEdBasis ';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.MICRO_ENTITY_GROSS_CERTIF_IN	IS 'Micro-Gross income basis cert value cert1/cert2.';  
COMMENT ON COLUMN 	ENTITY_CHANGE_REQUEST.MICRO_ENTITY_INST_CERTIF_CT	IS 'Micro-Institution of Higher Education Basis cert category InstitutionOfHigherEdBasisCert1/InstitutionOfHigherEdBasisCert2.';

