CREATE 	TABLE 	USER_SIGNATURE (
  FK_USER_REQUEST_ID			        NUMBER(15)		            NOT NULL,	
  USER_SIGNATURE_ID			        	NUMBER(15)					PRIMARY KEY,  
  SUBMITTER_SIGNATURE_TX				VARCHAR2(150),
  SUBMITTER_FULL_NAME_TX	  			VARCHAR2(150)  
    );

ALTER 	TABLE 	USER_SIGNATURE
ADD CONSTRAINT RI_UR_US
FOREIGN KEY (FK_USER_REQUEST_ID)
REFERENCES USER_REQUEST(USER_REQUEST_ID);

CREATE SEQUENCE PK_USER_SIGNATURE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
/
CREATE OR REPLACE TRIGGER 	PK_USER_SIGNATURE_TRIGGER
  BEFORE INSERT ON USER_SIGNATURE
 FOR EACH ROW
BEGIN
  SELECT PK_USER_SIGNATURE_SEQ.nextval
    INTO :new.USER_SIGNATURE_ID
    FROM dual;
END;
/

COMMENT ON TABLE USER_SIGNATURE IS 'Table to store the user signature details changes as draft in PAIR database until the user submits to make final changes in PALM database.Once the final submission is made to PALM the records are used as audit logs for any future user queries.';

COMMENT ON COLUMN 	USER_SIGNATURE.FK_USER_REQUEST_ID	IS 'Foreign key mapped to USER_REQUEST table '; 
COMMENT ON COLUMN 	USER_SIGNATURE.USER_SIGNATURE_ID	IS 'Primary Key '; 
COMMENT ON COLUMN 	USER_SIGNATURE.SUBMITTER_SIGNATURE_TX	IS 'User signature entered from PAIR admin ';  
COMMENT ON COLUMN 	USER_SIGNATURE.SUBMITTER_FULL_NAME_TX	IS 'User common name entered from PAIR admin ';
