CREATE TABLE USER_REQUEST (
USER_REQUEST_ID	  			NUMBER(15) 		  	NOT NULL,	
FK_USER_ID		    		VARCHAR2(15)  		NOT NULL,		 
CREATE_TS		      		TIMESTAMP		    NOT NULL,
LAST_MODIFIED_TS 			TIMESTAMP		    NOT NULL,
REQUEST_CT		  			VARCHAR2(15) 		NOT NULL,
REQUEST_STATUS_CT			VARCHAR2(10) 		NOT NULL,
REQUEST_STATUS_TX			VARCHAR2(256),
REGISTERED_ATTORNEY_AUTH_CT	VARCHAR2(15),
INVENTOR_CT					VARCHAR2(5),	
SUBMITTER_REGISTRATION_NO	VARCHAR2(6),
CONTACT_FULL_NM	 			VARCHAR2(150), 
CONTACT_TELEPHONE_NO_TX	 	VARCHAR2(25), 
CONTACT_EMAIL_TX		 	VARCHAR2(129), 
USER_COMMENT_TX				VARCHAR2(4000),
CREATE_USER_ID				VARCHAR2(20)		NOT NULL,
LAST_MODIFIED_USER_ID		VARCHAR2(20)		NOT NULL,
LOCK_CONTROL_NO				NUMBER(10)		DEFAULT 1 NOT NULL,
DELETE_IN					VARCHAR2(1)    	DEFAULT 'N'
);
/
ALTER TABLE USER_REQUEST ADD CONSTRAINT 	PK_USER_REQUEST 	PRIMARY KEY      (USER_REQUEST_ID);
/
CREATE SEQUENCE PK_USER_REQUEST_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE; 
/
CREATE OR REPLACE TRIGGER 	PK_USER_REQUEST_PK_TRIGGER
  BEFORE INSERT ON USER_REQUEST
 FOR EACH ROW
BEGIN
  SELECT PK_USER_REQUEST_SEQ.nextval
    INTO :new.USER_REQUEST_ID
    FROM dual;
END;
/

ALTER 	TABLE 	USER_REQUEST
ADD CONSTRAINT RI_PUD_UR
FOREIGN KEY (FK_USER_ID)
REFERENCES PAIR_USER_DN(USER_ID);
  
ALTER TABLE USER_REQUEST
ADD CONSTRAINT UK_USER_REQUEST UNIQUE (FK_USER_ID, CREATE_TS);

ALTER TABLE USER_REQUEST
ADD CONSTRAINT CK_USER_REQUEST_STATUS
  CHECK (REQUEST_STATUS_CT IN ('Saved', 'Submitted', 'Deleted', 'Failed'));
  
ALTER TABLE USER_REQUEST
ADD CONSTRAINT CK_USER_REQUEST_INVENTOR
  CHECK (INVENTOR_CT  IN ('JINS', 'JIN', 'INV'));
  
ALTER TABLE USER_REQUEST
ADD CONSTRAINT CK_USER_REQUEST_DELETE
  CHECK (DELETE_IN  IN ('Y', 'N'));
  
ALTER TABLE USER_REQUEST
ADD CONSTRAINT CK_UR_REQUEST_CT
  CHECK (REQUEST_CT   IN ('Entity Status', 'Customer Number', 'Address Change'));
  
ALTER TABLE USER_REQUEST
ADD CONSTRAINT CK_UR_REGISTERED_ATTORNEY_AUTH
  CHECK (REGISTERED_ATTORNEY_AUTH_CT   IN ('POA', 'Representative'));

  
COMMENT ON TABLE USER_REQUEST IS 'Master table to store the entity change/customer number/update address detail common changes as draft in PAIR database until the user submits to make final changes in PALM database.Once the final submission is made to PALM the records are used as audit logs for any future user queries.';

COMMENT ON COLUMN 	USER_REQUEST.USER_REQUEST_ID	IS 'Surrogate key for identification purposes.';  
COMMENT ON COLUMN 	USER_REQUEST.FK_USER_ID	IS 'Surrogate key to the user.'; 
COMMENT ON COLUMN 	USER_REQUEST.REGISTERED_ATTORNEY_AUTH_CT	IS 'Register Attorney Type POA/Representative.';  
COMMENT ON COLUMN 	USER_REQUEST.INVENTOR_CT	IS 'Indepentor inventor type Single Joint Inventor(JIN)/Several Joint InventorS (JINS)/Sole inventor (INV) ';  
COMMENT ON COLUMN 	USER_REQUEST.SUBMITTER_REGISTRATION_NO	IS 'Submitter/User Registration Number populated from USER_DN table.';  
COMMENT ON COLUMN 	USER_REQUEST.REQUEST_CT	IS 'Type of Request Entity Change/Customer Number/Address Change.';
COMMENT ON COLUMN 	USER_REQUEST.REQUEST_STATUS_CT	IS 'Status of Request Saved/Submitted/Failed/Deleted.';
COMMENT ON COLUMN 	USER_REQUEST.REQUEST_STATUS_TX	IS 'Field to store detailed success/Failure messages.';
COMMENT ON COLUMN 	USER_REQUEST.CONTACT_FULL_NM	IS 'Point of contact Full Name.';
COMMENT ON COLUMN 	USER_REQUEST.CONTACT_TELEPHONE_NO_TX	IS 'Point of Contact (POC) Telephone Number.';
COMMENT ON COLUMN 	USER_REQUEST.CONTACT_EMAIL_TX	IS 'Point of Contact (POC) Email.';
COMMENT ON COLUMN 	USER_REQUEST.CREATE_TS	IS 'Create Time Stamp of the request.';
COMMENT ON COLUMN 	USER_REQUEST.LAST_MODIFIED_TS	IS 'Last Modified Time Stamp of the request..';
COMMENT ON COLUMN 	USER_REQUEST.CREATE_USER_ID	IS 'Created USer Id of the request..';
COMMENT ON COLUMN 	USER_REQUEST.LAST_MODIFIED_USER_ID	IS 'Last modified user ID of the request..';
COMMENT ON COLUMN 	USER_REQUEST.USER_COMMENT_TX	IS 'Any comments from PURM users.';
COMMENT ON COLUMN 	USER_REQUEST.LOCK_CONTROL_NO	IS 'Lock in control value.';
COMMENT ON COLUMN 	USER_REQUEST.DELETE_IN	IS 'Delete Indicator Y or N.';