//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 07:58:10 PM EDT 
//


package gov.uspto.patent.privatePair.score.scoreService.MegaItemDetailImpl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for megaItemDetailInput-message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="megaItemDetailInput-message"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MegaItemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SequenceNumbers" type="{http://webservices.score.uspto.gov/}sequence-list-numbers-type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "megaItemDetailInput-message", propOrder = {
    "megaItemId",
    "sequenceNumbers"
})
public class MegaItemDetailInputMessage {

    @XmlElement(name = "MegaItemId", required = true)
    protected String megaItemId;
    @XmlElement(name = "SequenceNumbers", required = true)
    protected SequenceListNumbersType sequenceNumbers;

    /**
     * Gets the value of the megaItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegaItemId() {
        return megaItemId;
    }

    /**
     * Sets the value of the megaItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegaItemId(String value) {
        this.megaItemId = value;
    }

    /**
     * Gets the value of the sequenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceListNumbersType }
     *     
     */
    public SequenceListNumbersType getSequenceNumbers() {
        return sequenceNumbers;
    }

    /**
     * Sets the value of the sequenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceListNumbersType }
     *     
     */
    public void setSequenceNumbers(SequenceListNumbersType value) {
        this.sequenceNumbers = value;
    }

}
