--SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE IF EXISTS USER_REQUEST;

CREATE TABLE USER_REQUEST (
USER_REQUEST_ID	  NUMBER(15) CONSTRAINT PK_USER_REQUEST PRIMARY KEY ASC AUTOINCREMENT NOT NULL,
FK_USER_ID		    VARCHAR2(15)  	NOT NULL,		 
CREATE_TS		      TIMESTAMP		    NOT NULL,
LAST_MODIFIED_TS 	TIMESTAMP		    NOT NULL,
TYPE_OF_REQUEST	  VARCHAR2(20) 		NOT NULL,
REQUEST_STATUS_CT	VARCHAR2(10) 		NOT NULL,
REQUEST_DESCRIPTION_TX			      VARCHAR2(256),
SUBMITTER_FULL_NAME			          VARCHAR2(150),
SUBMITTER_SIGNATURE_TX			      VARCHAR2(4000),
SUBMITTER_REGISTRATION_NO			    CHAR(6),
CONTACT_FULL_NM	 			            VARCHAR2(150), 
CONTACT_TELEPHONE_NO_TX	 		      VARCHAR2(25), 
CONTACT_EMAIL_TX		 		          VARCHAR2(129), 
USER_COMMENTS_TX				          VARCHAR2(4000),
CREATE_USER_ID				            VARCHAR2(20),
LAST_MODIFIED_USER_ID			        VARCHAR2(20),
LOCK_CONTROL_NO				            NUMBER(10),
DELETE_IN					                VARCHAR2(1)    
);

--COMMENT ON COLUMN 	USER_REQUEST. USER_REQUEST_ID	IS 'Surrogate key for identification purposes. ';  
--COMMENT ON COLUMN 	USER_REQUEST. FK_USER_ID	IS 'Surrogate key to the user. ';  

ALTER TABLE USER_REQUEST ADD CONSTRAINT PK_USER_REQUEST PRIMARY KEY (USER_REQUEST_ID);

CREATE OR REPLACE TRIGGER 	PK_USER_REQUEST_PK_TRIGGER
  BEFORE INSERT ON USER_REQUEST
 FOR EACH ROW
BEGIN
  SELECT PK_USER_REQUEST_SEQ.nextval
    INTO :new.USER_REQUEST_ID
    FROM dual;
END;
