//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:25:58 AM EDT 
//


package gov.uspto.patent.privatePair.score.scoreService.MetaData;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import gov.uspto.patent.privatePair.score.scoreService.AppListImpl.ApplicationNumbersType;
import gov.uspto.patent.privatePair.score.scoreService.AppListImpl.DateRange;
import gov.uspto.patent.privatePair.score.scoreService.MegaData.MegaItemProcessCodeType;
import gov.uspto.patent.privatePair.score.scoreService.MegaData.MegaItemRecordType;
import gov.uspto.patent.privatePair.score.scoreService.MegaData.MegaItemRecordsType;
import gov.uspto.patent.privatePair.score.scoreService.MegaData.MegaItemsInputMessage;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemDetailImpl.MegaItemContentType;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemDetailImpl.MegaItemDetailInputMessage;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemDetailImpl.MegaItemDetailsType;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemDetailImpl.SequenceListNumbersType;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemVersionHistory.MegaItemVerHistoryInputMessage;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemVersionHistory.MegaItemVersionType;
import gov.uspto.patent.privatePair.score.scoreService.MegaItemVersionHistory.MegaItemVersionsType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.uspto.patent.privatePair.score.scoreService.MetaData package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
    private final static QName _ElementMegaItemDetailInputMessage_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemDetailInputMessage");
    private final static QName _ElementMegaItemDetailsType_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemDetailsType");
    private final static QName _ElementApplicationNumbersType_QNAME = new QName("http://webservices.score.uspto.gov/", "element-applicationNumbersType");
    private final static QName _ElementBeginEndDates_QNAME = new QName("http://webservices.score.uspto.gov/", "element-beginEndDates");
	private final static QName _ElementMegaItemVerHistoryInputMessage_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemVerHistoryInputMessage");
    
	private final static QName _ElementMegaItemVersionsType_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemVersionsType");
	private final static QName _ElementMegaItemRecordsType_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemRecordsType");
	private final static QName _ElementMegaItemsInputMessage_QNAME = new QName("http://webservices.score.uspto.gov/", "element-megaItemsInputMessage");
    private final static QName _ElementMetaDataRecordsType_QNAME = new QName("http://webservices.score.uspto.gov/", "element-metaDataRecordsType");
    private final static QName _ElementString_QNAME = new QName("http://webservices.score.uspto.gov/", "element-string");

    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.uspto.patent.privatePair.score.scoreService.MetaData
     * 
     */
    public ObjectFactory() {
    }
    /**
     * Create an instance of {@link MegaItemDetailInputMessage }
     *
     */
    public MegaItemDetailInputMessage createMegaItemDetailInputMessage() {
        return new MegaItemDetailInputMessage();
    }

    /**
     * Create an instance of {@link MegaItemDetailsType }
     *
     */
    public MegaItemDetailsType createMegaItemDetailsType() {
        return new MegaItemDetailsType();
    }

    /**
     * Create an instance of {@link SequenceListNumbersType }
     *
     */
    public SequenceListNumbersType createSequenceListNumbersType() {
        return new SequenceListNumbersType();
    }

    /**
     * Create an instance of {@link MegaItemContentType }
     *
     */
    public MegaItemContentType createMegaItemContentType() {
        return new MegaItemContentType();
    }

    /**
     * Create an instance of {@link ApplicationNumbersType }
     *
     */
    public ApplicationNumbersType createApplicationNumbersType() {
        return new ApplicationNumbersType();
    }

    /**
     * Create an instance of {@link DateRange }
     *
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link MegaItemVerHistoryInputMessage }
     * 
     */
    public MegaItemVerHistoryInputMessage createMegaItemVerHistoryInputMessage() {
        return new MegaItemVerHistoryInputMessage();
    }

    /**
     * Create an instance of {@link MegaItemVersionsType }
     * 
     */
    public MegaItemVersionsType createMegaItemVersionsType() {
        return new MegaItemVersionsType();
    }

    /**
     * Create an instance of {@link MegaItemVersionType }
     * 
     */
    public MegaItemVersionType createMegaItemVersionType() {
        return new MegaItemVersionType();
    }

    /**
     * Create an instance of {@link MetaDataRecordsType }
     * 
     */
    public MetaDataRecordsType createMetaDataRecordsType() {
        return new MetaDataRecordsType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }
    
    /**
     * Create an instance of {@link MegaItemRecordsType }
     * 
     */
    public MegaItemRecordsType createMegaItemRecordsType() {
        return new MegaItemRecordsType();
    }

    /**
     * Create an instance of {@link MegaItemsInputMessage }
     * 
     */
    public MegaItemsInputMessage createMegaItemsInputMessage() {
        return new MegaItemsInputMessage();
    }

    /**
     * Create an instance of {@link MegaItemRecordType }
     * 
     */
    public MegaItemRecordType createMegaItemRecordType() {
        return new MegaItemRecordType();
    }

    /**
     * Create an instance of {@link MegaItemProcessCodeType }
     * 
     */
    public MegaItemProcessCodeType createMegaItemProcessCodeType() {
        return new MegaItemProcessCodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemDetailInputMessage }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemDetailInputMessage")
    public JAXBElement<MegaItemDetailInputMessage> createElementMegaItemDetailInputMessage(MegaItemDetailInputMessage value) {
        return new JAXBElement<MegaItemDetailInputMessage>(_ElementMegaItemDetailInputMessage_QNAME, MegaItemDetailInputMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemDetailsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemDetailsType")
    public JAXBElement<MegaItemDetailsType> createElementMegaItemDetailsType(MegaItemDetailsType value) {
        return new JAXBElement<MegaItemDetailsType>(_ElementMegaItemDetailsType_QNAME, MegaItemDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationNumbersType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-applicationNumbersType")
    public JAXBElement<ApplicationNumbersType> createElementApplicationNumbersType(ApplicationNumbersType value) {
        return new JAXBElement<ApplicationNumbersType>(_ElementApplicationNumbersType_QNAME, ApplicationNumbersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateRange }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-beginEndDates")
    public JAXBElement<DateRange> createElementBeginEndDates(DateRange value) {
        return new JAXBElement<DateRange>(_ElementBeginEndDates_QNAME, DateRange.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemVerHistoryInputMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemVerHistoryInputMessage")
    public JAXBElement<MegaItemVerHistoryInputMessage> createElementMegaItemVerHistoryInputMessage(MegaItemVerHistoryInputMessage value) {
        return new JAXBElement<MegaItemVerHistoryInputMessage>(_ElementMegaItemVerHistoryInputMessage_QNAME, MegaItemVerHistoryInputMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemVersionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemVersionsType")
    public JAXBElement<MegaItemVersionsType> createElementMegaItemVersionsType(MegaItemVersionsType value) {
        return new JAXBElement<MegaItemVersionsType>(_ElementMegaItemVersionsType_QNAME, MegaItemVersionsType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataRecordsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-metaDataRecordsType")
    public JAXBElement<MetaDataRecordsType> createElementMetaDataRecordsType(MetaDataRecordsType value) {
        return new JAXBElement<MetaDataRecordsType>(_ElementMetaDataRecordsType_QNAME, MetaDataRecordsType.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemRecordsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemRecordsType")
    public JAXBElement<MegaItemRecordsType> createElementMegaItemRecordsType(MegaItemRecordsType value) {
        return new JAXBElement<MegaItemRecordsType>(_ElementMegaItemRecordsType_QNAME, MegaItemRecordsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MegaItemsInputMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-megaItemsInputMessage")
    public JAXBElement<MegaItemsInputMessage> createElementMegaItemsInputMessage(MegaItemsInputMessage value) {
        return new JAXBElement<MegaItemsInputMessage>(_ElementMegaItemsInputMessage_QNAME, MegaItemsInputMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.score.uspto.gov/", name = "element-string")
    public JAXBElement<String> createElementString(String value) {
        return new JAXBElement<String>(_ElementString_QNAME, String.class, null, value);
    }

}
